version: '3.4'

services:
  # reviewsapi:
  #   image: reviewsapi
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  node:
    image: sdc-node
    container_name: sdc-node
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: node.Dockerfile

  postgres:
    image: sdc-postgres
    container_name: sdc-postgres
    ports:
      - 3006:5432  # 5432:5432 for ec2 3006:5432 on local
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myCoolPassword
    build:
      context: .
      dockerfile: postgres.Dockerfile

  nginx:
    image: sdc-nginx
    container_name: sdc-nginx
    ports:
      - 3005:3000 # move local port (left) off 3000 if deploying locally
    build:
      context: .
      dockerfile: nginx.Dockerfile

  node2: # only need locally
    image: sdc-node2
    container_name: sdc-node2
    ports:
      - 3001:3000 # move local port (left) off 3000 if deploying locally
    build:
      context: .
      dockerfile: node.Dockerfile