version: '3.4'

services:
  # reviewsapi:
  #   image: reviewsapi
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  node:
    image: sdc-node
    container_name: sdc-node
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: node.Dockerfile
    depends_on:
      - postgres

  postgres:
    image: sdc-postgres
    container_name: sdc-postgres
    ports:
      - 3001:5432
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myCoolPassword
    build:
      context: .
      dockerfile: postgres.Dockerfile